#pragma once

#define DEFAULT_WINDOW_WIDTH 450
#define DEFAULT_WINDOW_HEIGHT 150
#define DEFAULT_Y 50
#define MAX_LOADSTRING 100
#define MAX_WINDOW_WIDTH 1500
#define MAX_WINDOW_HEIGHT 800
#define MIN_WINDOW_WIDTH 400
#define MIN_WINDOW_HEIGHT 280
#define ID_TIMER_TAKESCREEN 1
#define TIMEOUT_WINDOW_DISAPPEAR 300
#define BACKWND_TRANSPARENCY 150
#define SCROLLBAR_WIDTH 20