#pragma once

#define DEFAULT_WINDOW_WIDTH 450
#define DEFAULT_WINDOW_HEIGHT 150
#define DEFAULT_Y 50
#define MAX_LOADSTRING 100
#define MAX_SCREEN_WIDTH 1500
#define MAX_SCREEN_HEIGHT 800
#define SCREENSHOT_DISPLAY_BORDER 50
#define ID_TIMER_TAKESCREEN 1
#define TIMEOUT_WINDOW_DISAPPEAR 1000