#pragma once

#define DEFAULT_WINDOW_WIDTH 450
#define DEFAULT_WINDOW_HEIGHT 150
#define DEFAULT_Y 50
#define MAX_LOADSTRING 100
#define DEFAULT_WINDOW_EXTENDED_WIDTH 1200
#define DEFAULT_WINDOW_EXTENDED_HEIGHT 700
#define ID_TIMER_TAKESCREEN 1